var articles_list = [{
    "like":true,
    "date":"2012/07/31",
    "week":"Tue",
    "time":"16:19",
    "sign":"hualien",
    "title":"[遊戲] 貪吃蛇III",
    "file":"snake3.txt",
    },{
    "like":true,
    "date":"2012/07/31",
    "week":"Tue",
    "time":"16:25",
    "sign":"hualien",
    "title":"[遊戲] 貪吃蛇III 修改第二版",
    "file":"snake3.2.txt",
    },{
    "like":true,
    "date":"2012/08/01",
    "week":"Wed",
    "time":"17:01",
    "sign":"hualien",
    "title":"[作品] pi 蛇 4.6",
    "file":"snake4.6.txt",
    },{
    "like":true,
    "date":"2012/08/01",
    "week":"Wed",
    "time":"19:10",
    "sign":"hualien",
    "title":"[程式] Brainfuck",
    "file":"brainfuck.txt",
    },{
    "like":false,
    "date":"2012/08/01",
    "week":"Wed",
    "time":"17:31",
    "sign":"hualien",
    "title":"[程式] Matrix_II",
    "file":"matrix2.txt",
    },{
    "like":true,
    "date":"2012/07/31",
    "week":"Tue",
    "time":"17:18",
    "sign":"hualien",
    "title":"[程式] Petri dish---培養皿",
    "file":"petridish.txt",
    },{
    "like":true,
    "date":"2012/08/02",
    "week":"Thu",
    "time":"",
    "sign":"hualien",
    "title":"[作品] 貪吃蛇 5",
    "file":"snake5.txt",
    },{
    "like":false,
    "date":"2012/08/02",
    "week":"Thu",
    "time":"17:28",
    "sign":"hualien",
    "title":"[程式] Mouse Board",
    "file":"mouseboard.txt",
    },{
    "like":true,
    "date":"2012/08/01",
    "week":"Wed",
    "time":"17:50",
    "sign":"hualien",
    "title":"[作品] 串珠",
    "file":"chain.txt",
    },{
    "like":true,
    "date":"2012/08/02",
    "week":"Thu",
    "time":"17:40",
    "sign":"hualien",
    "title":"[作品] 新風格首頁",
    "file":"newHomePage.txt",
    },{
    "like":true,
    "base":true,
    "date":"2012/08/02",
    "week":"Thu",
    "time":"17:45",
    "sign":"hualien",
    "title":"[常用] 個人常用的程式",
    "file":"commonUse.txt",
    },{
    "like":true,
    "date":"2012/08/07",
    "week":"Tue",
    "time":"11:04",
    "sign":"hualien",
    "title":"[作品] Universe",
    "file":"universe.txt",
    "push":"universe_p.txt",
    },{
    "like":true,
    "date":"2012/08/19",
    "week":"Sun",
    "time":"22:31",
    "sign":"hualien",
    "re":true,
    "title":"[作品] 新風格首頁",
    "file":"newHomePage_re.txt",
    },{
    "like":true,
    "date":"2012/09/26",
    "week":"Wed",
    "time":"23:59",
    "sign":"nctu",
    "re":true,
    "title":"[作品] 新風格首頁",
    "file":"newHomePage_re2.txt",
    "push":"newHomePage_re2_p.txt",
    },{
    "like":true,
    "date":"2013/02/24",
    "week":"Sun",
    "time":"21:32",
    "sign":"hualien",
    "re":true,
    "title":"[作品] Universe",
    "file":"universe_re.txt",
    },{
    "like":true,
    "date":"2013/08/20",
    "week":"Tue",
    "time":"21:34",
    "sign":"hualien",
    "title":"[作品] wvim",
    "file":"wvim.txt",
    },{
    "like":true,
    "date":"2013/10/12",
    "week":"Sat",
    "time":"20:13",
    "sign":"nctu",
    "title":"[作品] 新風格首頁 & Universe1.2",
    "file":"update_on_homepage_and_universe.txt",
    "push":"update_on_homepage_and_universe_p.txt",
    },{
    "like":true,
    "date":"2014/01/10",
    "week":"Fri",
    "time":"15:59",
    "sign":"nctu",
    "title":"[有趣] 自產生程式",
    "file":"quine.txt",
    "re":false,
}];
